---
title: "4.2 BE for left-censored data"
author: "Yoshinari Suzuki"
date: "2024-11-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# パッケージの読み込み
```{r}
library(tidyverse) # データフレームを操作するための{dyplyr}{tidyr}や作図用のggplot2等を一度に呼び出せる
library(scales) # 対数軸を使用するため
library(readxl) # Excelファイルを読み込む
library(cowplot) # 複数のプロットを軸を揃えて並べる
# library(statip) # 最頻値を計算する関数 mfv() があるが、複数の値を返すことがあるので注意
library(HDInterval) # 最高密度区間 (HDI) を計算する

# ggplot2用の設定
theme_set(
  theme_bw() +
  theme(
    panel.grid.minor = element_line(linetype = "blank"), 
    axis.text = element_text(colour = "black"),
    legend.position="bottom",
    text=element_text(size=12)
  )
)

# ベイズ推定を行うのに必要
library(cmdstanr) # RからCmdstanに指示を与えて、BE法を実行させる
library(bayesplot) # ベイズ推定の結果を視覚化する
library(posterior) # 事後分布

# MAP推定量を算出するための関数を設定
MAP <- function(x) {
  density_est <- density(x)
  map <- density_est$x[which.max(density_est$y)]
  return(map)
}
```

# データの読み込み及び作図
```{r}
data = readxl::read_xlsx("Excel_simulation.xlsx", sheet = 3)
# このデータは、幾何平均値=1, 幾何標準偏差=2の対数正規分布を仮定して生成した乱数で、LOD=0.3, LOQ=1を設定したものです

# 余分な列を削除
data <- data[,1:4]
```

# ベイズモデルの作成
```{r}
model_lognormal <- cmdstan_model("Lognormal_Censored.stan")
```

# 対数正規分布を仮定したベイズ推定
```{r}
N_thin <- 1
N_warmup <- 500
N_sampling <- 500
N_chain <- 4
N_new <- 50

gsd_int <- c(1,3) # Cauchy分布のパラメーター

standata <- list(
  N=nrow(data), Y_L=data$LB, Y_U=data$UB, gsd_int=gsd_int, N_new=N_new
)

fit_lognormal <- model_lognormal$sample(
  data = standata,
  parallel_chains = 4,
  chains = N_chain,
  thin = N_thin,
  iter_warmup = N_warmup * N_thin,
  iter_sampling = N_sampling * N_thin,
  save_warmup = TRUE,
  seed = 1, #
  adapt_delta = 0.80, # デフォルト値。必要に応じて変更する。0~1の実数を入力する。
  max_treedepth = 10  # デフォルト値。必要に応じて変更する。正の整数を入力する。
)

# trace plotで計算の収束具合を確認
color_scheme_set("gray")
plot1 <- fit_lognormal$draws(inc_warmup = TRUE) %>% 
  mcmc_trace(
    n_warmup = N_warmup,
    par=c("gm", "gsd", "lp__"), # 描画する変数を指定
    facet_args = list(ncol = 1)
  ) +
    ggplot2::geom_line(alpha=0.25, size=0.75) +
    ggplot2::theme(
      text=element_text(size=14),
      legend.position = "bottom"  # 凡例を下部に移動
    ) +
    xlab("Iteration") + ylab("Value")

# 事後分布のdensity plot
plot2 <- fit_lognormal$draws() %>% 
  mcmc_dens_overlay(
    par=c("gm", "gsd", "lp__"),
    facet_args = list(ncol = 1)
  ) +
    ggplot2::geom_density(aes(fill=Chain), alpha=0.25) +
    ggplot2::scale_fill_grey(name = "Chain") +
    ggplot2::theme_bw() +
    ggplot2::theme(
      panel.grid.minor = element_line(linetype = "blank"), 
      axis.text = element_text(colour = "black"),
      legend.position="bottom",
      text=element_text(size=14)
    ) +
    ggplot2::scale_y_continuous(expand = c(0, 0)) +
    ggplot2::coord_flip() +
    xlab("Value") + ylab("Density")

cowplot::plot_grid(plot1, plot2, align = "h", rel_widths = c(1, 0.5), scale = 0.95)
ggsave("trace + density plot.png", dpi=300, width = 12, height = 6)

# その他収束の判断
# R_hatが1.1より大きい推定値が無いか確認
fit_lognormal %>% bayesplot::rhat() %>% mcmc_rhat_hist()

# N_eff率が0.1以下の推定値が無いか確認 
fit_lognormal %>% bayesplot::neff_ratio() %>% mcmc_neff_hist()

# BE法の結果に関する要約
summary.fit_lognormal <- fit_lognormal$summary()

# 全ての事後分布をデータフレームに
d.ms_lognormal <- fit_lognormal$draws() %>% as_draws_df()

# 代表的な推定値の統計量
fit_lognormal$summary(
  variables = c("gm", "gsd", "mean_est", "sd_est", "lp__"),
  posterior::default_summary_measures()[c(1,3)],
  quantiles = ~ quantile2(., probs = c(0.025, 0.25, 0.5, 0.75, 0.975)),
  posterior::default_convergence_measures()
)

# MAPの計算
MAP(d.ms_lognormal$gm)
MAP(d.ms_lognormal$gsd)

# HDIの計算
HDInterval::hdi(d.ms_lognormal$gm, 0.95)
HDInterval::hdi(d.ms_lognormal$gsd, 0.95)

# 計算に要した時間 (秒)
fit_lognormal$time()
```

# 実行環境の情報を出力
```{r}
sessionInfo()
```

